---
abstract: 'Sinatra-ish Simple and Clear web application framework'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kossy
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Class::Accessor::Lite: 0
  Cwd: 0
  Data::Section::Simple: 0
  File::Basename: 0
  File::ShareDir: 0
  HTML::FillInForm::Lite: 1.11
  HTTP::Message: 0
  Hash::MultiValue: 0
  JSON: 0
  Kossy::Validator: 0.01
  Number::Format: 0
  Plack: 0
  Plack::Middleware::ReverseProxy: 0
  Plack::Middleware::Static: 0
  Router::Simple: 0
  Scalar::Util: 0
  Test::More: 0.88
  Text::Xslate: 1.6001
  Text::Xslate::Bridge::TT2Like: 0
  Try::Tiny: 0.09
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kazeburo/Kossy.git
version: 0.20
